-- ============================================================
-- banproof.me — D1 Database Schema
-- Apply: wrangler d1 execute bp-core-prod --file=schema.sql
-- ============================================================

-- Users table: auth, subscription tier, Stripe link
CREATE TABLE IF NOT EXISTS users (
    id                  TEXT PRIMARY KEY,          -- UUID generated by the worker
    email               TEXT UNIQUE NOT NULL,
    stripe_customer_id  TEXT,
    plan_tier           TEXT NOT NULL DEFAULT 'free',   -- 'free' | 'pro' | 'admin'
    subscription_status TEXT NOT NULL DEFAULT 'active', -- 'active' | 'canceled' | 'past_due'
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email              ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_stripe_customer_id ON users (stripe_customer_id);

-- CMS content: sports/eBay tool copy & config served to the front-end
CREATE TABLE IF NOT EXISTS cms_content (
    id         INTEGER  PRIMARY KEY AUTOINCREMENT,
    slug       TEXT     UNIQUE NOT NULL,
    title      TEXT     NOT NULL,
    body       TEXT     NOT NULL DEFAULT '',   -- Markdown content
    category   TEXT     NOT NULL DEFAULT 'general', -- 'sports' | 'ebay' | 'general'
    published  INTEGER  NOT NULL DEFAULT 1,   -- 0 = draft, 1 = live
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cms_slug     ON cms_content (slug);
CREATE INDEX IF NOT EXISTS idx_cms_category ON cms_content (category);

-- Sessions table: maps session tokens to users
CREATE TABLE IF NOT EXISTS sessions (
    token      TEXT     PRIMARY KEY,               -- crypto.randomUUID()
    user_id    TEXT     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);

CREATE TABLE IF NOT EXISTS audit_log (
    id         INTEGER  PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT     REFERENCES users (id) ON DELETE SET NULL,
    action     TEXT     NOT NULL,        -- 'login' | 'upgrade' | 'api_call' | etc.
    metadata   TEXT,                    -- JSON blob with extra context
    ip         TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_user_id ON audit_log (user_id);
