-- ============================================================
-- banproof.me — D1 Database Schema
-- Apply: wrangler d1 execute bp-core-prod --file=schema.sql
-- ============================================================

-- Users table: auth, subscription tier, Stripe link
CREATE TABLE IF NOT EXISTS users (
    id                  TEXT PRIMARY KEY,          -- UUID generated by the worker
    email               TEXT UNIQUE NOT NULL,
    password_hash       TEXT,
    role                TEXT NOT NULL DEFAULT 'user',   -- 'user' | 'admin' | 'sudo'
    stripe_customer_id  TEXT,
    plan_tier           TEXT NOT NULL DEFAULT 'free',   -- 'free' | 'pro' | 'agency'
    subscription_status TEXT NOT NULL DEFAULT 'active', -- 'active' | 'canceled' | 'past_due'
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email              ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_stripe_customer_id ON users (stripe_customer_id);

-- CMS content: sports/eBay tool copy & config served to the front-end
CREATE TABLE IF NOT EXISTS cms_content (
    id         INTEGER  PRIMARY KEY AUTOINCREMENT,
    slug       TEXT     UNIQUE NOT NULL,
    title      TEXT     NOT NULL,
    body       TEXT     NOT NULL DEFAULT '',   -- Markdown content
    category   TEXT     NOT NULL DEFAULT 'general', -- 'sports' | 'ebay' | 'general'
    published  INTEGER  NOT NULL DEFAULT 1,   -- 0 = draft, 1 = live
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cms_slug     ON cms_content (slug);
CREATE INDEX IF NOT EXISTS idx_cms_category ON cms_content (category);

-- Sessions table: maps session tokens to users
CREATE TABLE IF NOT EXISTS sessions (
    id             TEXT     PRIMARY KEY,
    user_id        TEXT     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    access_token   TEXT     NOT NULL,
    refresh_token  TEXT     NOT NULL,
    expires_at     DATETIME NOT NULL,
    revoked_at     DATETIME,
    ip_address     TEXT,
    user_agent     TEXT,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_access_token ON sessions (access_token);
CREATE INDEX IF NOT EXISTS idx_sessions_refresh_token ON sessions (refresh_token);

CREATE TABLE IF NOT EXISTS audit_log (
    id         INTEGER  PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT     REFERENCES users (id) ON DELETE SET NULL,
    action     TEXT     NOT NULL,        -- 'login' | 'upgrade' | 'api_call' | etc.
    metadata   TEXT,                    -- JSON blob with extra context
    ip         TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_user_id ON audit_log (user_id);

-- Admin audit log: tracking admin actions
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id             INTEGER  PRIMARY KEY AUTOINCREMENT,
    admin_id       TEXT     NOT NULL REFERENCES users (id),
    action         TEXT     NOT NULL,
    target_user_id TEXT     REFERENCES users (id),
    metadata       TEXT,
    ip_address     TEXT,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Subscriptions table: mirrors Stripe status
CREATE TABLE IF NOT EXISTS subscriptions (
    id                     TEXT     PRIMARY KEY,
    user_id                TEXT     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    stripe_subscription_id TEXT,
    plan_tier              TEXT     NOT NULL,
    status                 TEXT     NOT NULL,
    current_period_end     DATETIME,
    auto_renew             INTEGER  NOT NULL DEFAULT 1,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Inquiries table: lead generation for Agency tier
CREATE TABLE IF NOT EXISTS inquiries (
    id           TEXT     PRIMARY KEY,
    user_id      TEXT     REFERENCES users (id),
    company      TEXT,
    email        TEXT     NOT NULL,
    project_type TEXT     NOT NULL,
    status       TEXT     NOT NULL DEFAULT 'pending',
    metadata     TEXT,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Banproof signals: specific AI analysis output
CREATE TABLE IF NOT EXISTS signals (
    id         TEXT     PRIMARY KEY,
    user_id    TEXT     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       TEXT     NOT NULL, -- 'SPORTS' | 'INVENTORY' | etc.
    score      REAL,
    metadata   TEXT,     -- JSON blob
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_signals_user_id ON signals (user_id);
