name = "banproof-core"
main = "src/index.ts"
compatibility_date = "2026-04-01"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "bp-core-prod"
database_id = "54e1a408-4b81-4ca5-b6a4-c2314dc0cf46"

[[kv_namespaces]]
binding = "CACHE"
id = "af8eb071fce34b5eafbdeb1badd93876"

[[kv_namespaces]]
binding = "INFRA_SECRETS"
id = "b9824d3280c54573a24137c7e7143b33"

[[workflows]]
name = "banproof-engine"
binding = "ENGINE"
class_name = "BanproofEngine"

[ai]
binding = "AI"
